repos:
  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt
        entry: bash scripts/update_requirements.sh
        language: system
        files: ^requirements\.txt$
