"""Create user table

Revision ID: ae9823b9ddca
Revises: d86a1f8779a6
Create Date: 2025-04-28 20:01:37.541001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9823b9ddca'
down_revision: Union[str, None] = 'd86a1f8779a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_genre', table_name='movies')
    op.drop_index('ix_movies_id', table_name='movies')
    op.drop_index('ix_movies_price', table_name='movies')
    op.drop_index('ix_movies_title', table_name='movies')
    op.drop_table('movies')
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.create_index('ix_movies_price', 'movies', ['price'], unique=False)
    op.create_index('ix_movies_id', 'movies', ['id'], unique=False)
    op.create_index('ix_movies_genre', 'movies', ['genre'], unique=False)
    # ### end Alembic commands ###
